// Vince Petrelli All Rights Reserved

#pragma once
#include "NativeGameplayTags.h"

/** 사용자 입력에 대한 커스텀 GamePlayTags 입니다.*/
namespace WarriorsGameplayTags
{
	/** Input Tags*/
	WARRIORS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move)
	WARRIORS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look)
	WARRIORS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipAxe)
	WARRIORS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnEquipAxe)
	WARRIORS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_Axe)
	WARRIORS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_Axe)

	/** Player Tags*/
	WARRIORS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Axe)
	WARRIORS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_UnEquip_Axe)
	WARRIORS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Axe)
	WARRIORS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy_Axe)
	WARRIORS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_HitPuase)
	WARRIORS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe)

	/** Player Event Tags*/
	WARRIORS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Axe)
	WARRIORS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_UnEquip_Axe)
	
	WARRIORS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_HitPuase)

	WARRIORS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_JumpToFinisher)
	WARRIORS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Light)
	WARRIORS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Heavy)

	/** Enemy Tags*/
	WARRIORS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Melee)
	WARRIORS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Ranged)
	WARRIORS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon)

	/** Shared Tags*/
	WARRIORS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_HitReact)
	WARRIORS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_Death)
	
	WARRIORS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit)
	WARRIORS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact)
	
	WARRIORS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_BaseDamage)
	
	WARRIORS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Dead)
	
}
